### PR TITLE
Improve compatibility with other frameworks and future OMF.

### PR DESCRIPTION
**Pull request by bobthecow**
- Move all autoloaded functions to `functions/`.

### CODE REVIEW

**Comment by scorphus** [comment]
@bobthecow How about removing `functions/_python.fish` as it really is replaced by `functions/__python.fish`?

**Comment by derekstavis** [comment]
Hm, I believe it's out of this PR's scope. I'd merge this one and then afterwards send another removing the file, as it would improve _traceability_.

**Comment by scorphus** [comment]
Sounds fair.

**Comment by scorphus** [comment]
Thank you, @bobthecow.

**Comment by bobthecow** [comment]
Sorry, I should have removed it. I imagine something got weird with git mv + the rename and I missed it.

**Comment by scorphus** [comment]
No problem! Yeah, I just thought the same... But, anyway, it's gone for good now. Nice job with the plugins, BTW

**Comment by bobthecow** [comment]
No problem!

**Pull request merged**
